from .states import sample_function
from .symbols import sample_function
from .geography import sample_function
from .rivers_dams import sample_function
from .names import sample_function
from .religion_culture import sample_function
from .law_constitution import sample_function
from .infrastructure import sample_function
from .defense import sample_function
from .travel_food import sample_function
from .utility import sample_function
from .education_exams import sample_function
from .sports_cricket import sample_function
from .cinema_bollywood import sample_function
from .music_instruments import sample_function
from .astro_space import sample_function
from .ayurveda_yoga import sample_function
from .indian_awards import sample_function
from .pollution_environment import sample_function
from .weather_climate import sample_function
from .festivals_customs import sample_function
from .languages_scripts import sample_function
from .inventions_discoveries import sample_function
from .traffic_transport import sample_function
from .crafts_fabrics import sample_function
from .indian_trivia import sample_function
from .emergency_contacts import sample_function
from .banking_finance import sample_function
from .careers_jobs import sample_function
from .agriculture import sample_function
from .market_prices import sample_function
from .indian_companies import sample_function
from .politics_governance import sample_function
from .states_and_neighbors import sample_function
from .ecommerce_data import sample_function
from .urban_rural_stats import sample_function
from .temples_festivals import sample_function
from .indian_units import sample_function
from .indian_schemes_benefits import sample_function
from .village_data import sample_function
from .identity_utils import sample_function
from .healthcare_info import sample_function
from .festivals_365 import sample_function
from .languages_distribution import sample_function
from .travel_routes import sample_function
from .indian_exports_imports import sample_function
from .state_budget_data import sample_function
from .legislature_data import sample_function
from .education_stats import sample_function
from .social_media_trends import sample_function
from .historical_places import sample_function
from .psychology_traditions import sample_function
from .rare_facts import sample_function
from .pyindia_cli import sample_function
